# Generated by Django 5.1.1 on 2024-09-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_comment_track_object_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
    ]
