# Generated by Django 5.1.1 on 2024-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_playlist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
